# .github/workflows/update-jira-ticket.yml
name: Update Jira Ticket

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Jira Ticket ID from branch name
      run: |
        # Extraer el ID de Jira que comienza con SCRUM- seguido de números
        TICKET_ID=$(echo "${{ github.head_ref }}" | grep -o 'SCRUM-[0-9]*')
        if [ -z "$TICKET_ID" ]; then
          echo "No Jira ticket ID found in the branch name. Skipping..."
          exit 0
        fi
        echo "Jira ticket ID: $TICKET_ID"
        echo "TICKET_ID=$TICKET_ID" >> $GITHUB_ENV

    - name: Fetch PR comments
      uses: octokit/request-action@v2.4.0
      id: fetch-comments
      with:
        route: GET /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Jira Ticket
      run: |
        echo "Updating Jira Ticket with comments from PR..."
        COMMENTS=$(echo '${{ steps.fetch-comments.outputs.data }}' | jq -r '.[] | "\(.user.login): \(.body)"' | jq -sRr @json)
        curl --request POST \
          --url "https://ingsoft1grupo1.atlassian.net/rest/api/3/issue/${{ env.TICKET_ID }}/comment" \
          --user '${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN }}' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{
            "body": {
              "type": "doc",
              "version": 1,
              "content": [
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "type": "text",
                      "text": '"$COMMENTS"'
                    }
                  ]
                }
              ]
            }
          }'
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_USER: ${{ secrets.JIRA_USER }}